run:
  timeout: 5m
  modules-download-mode: mod

linters:
  enable:
    - errcheck
    - gosimple
    - govet
    - ineffassign
    - staticcheck
    - unused
    - gofmt
    - misspell
    - unconvert
    - bodyclose
    - errorlint

linters-settings:
  gofmt:
    simplify: true

  misspell:
    locale: UK

  errcheck:
    exclude-functions:
      - (net/http.ResponseWriter).Write
      - fmt.Fprint
      - fmt.Fprintf
      - fmt.Fprintln

issues:
  exclude-rules:
    - path: _test\.go
      linters:
        - errcheck
        - unparam